info:
  build.version: $project.version$

spring:
  application:
    name: demo-mq

  profiles:
    active: '@project.active@'

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

feign:
  hystrix:
    enabled: true

  compression:
    request:
      mime-types:
        - text/xml
        - application/json
      min-request-size: 2048  #超过2048字节进行压缩

#熔断机制
hystrix:
  threadpool:
    default:
      coreSize: 1000  #并发执行的最大线程数，默认10
      maxQueueSize: 1000  #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500  #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #请求超时时间
 
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048



