server:
  port: '4003'



# rabbitmq配置
spring:
  rabbitmq:
    host: 192.168.14.116
    port: 5672
    username: root
    password: 123456

logging:
  level: 
    com.boande: INFO
  file: '/var/log/mq.log'